### ISSUE TITLE
th-orphans-0.12.0 could use revisions

### ISSUE THREAD

**Issue by Bodigrim** [mgsloan/th-orphans#37]
```
$ cabal unpack th-orphans-0.12.0
$ cd th-orphans-0.12.0
$ cabal build  -w ghc-9.2 --constraint 'th-reify-many == 0.1.8'
[1 of 1] Compiling Language.Haskell.TH.Instances

src/Language/Haskell/TH/Instances.hs:415:2: error:
    Duplicate instance declarations:
      instance Lift a => Lift (GHC.Real.Ratio a)
        -- Defined at src/Language/Haskell/TH/Instances.hs:415:2
      instance Integral a => Lift (GHC.Real.Ratio a)
        -- Defined in ‘Language.Haskell.TH.Syntax’
    |
415 | $(reifyManyWithoutInstances ''Lift [''Info, ''Loc] (const True) >>=
    |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
```

Removing constraint reveals another issue with package bounds:
```
$ cabal build -w ghc-9.2
[1 of 1] Compiling Language.Haskell.TH.Instances

src/Language/Haskell/TH/Instances.hs:415:2: error:
    • Could not deduce (Lift
                          (ghc-prim-0.8.0:GHC.Prim.State# ghc-prim-0.8.0:GHC.Prim.RealWorld
                           -> (# ghc-prim-0.8.0:GHC.Prim.State#
                                   ghc-prim-0.8.0:GHC.Prim.RealWorld,
                                 a #)))
        arising from a use of ‘lift’
        (maybe you haven't applied a function to enough arguments?)
      from the context: Lift a
        bound by the instance declaration
        at src/Language/Haskell/TH/Instances.hs:(415,2)-(416,17)
      or from: Quote m
        bound by the type signature for:
                   lift :: forall (m :: * -> *). Quote m => IO a -> m Exp
        at src/Language/Haskell/TH/Instances.hs:(415,2)-(416,17)
    • In the second argument of ‘appE’, namely ‘(lift x0_a5kE)’
      In the expression:
        (appE
           (conE
              ((Name (mkOccName "IO"))
                 (((NameG DataName) (mkPkgName "ghc-prim"))
                    (mkModName "GHC.Types")))))
          (lift x0_a5kE)
      In a case alternative:
          ghc-prim-0.8.0:GHC.Types.IO x0_a5kE
            -> (appE
                  (conE
                     ((Name (mkOccName "IO"))
                        (((NameG DataName) (mkPkgName "ghc-prim"))
                           (mkModName "GHC.Types")))))
                 (lift x0_a5kE)
    |
415 | $(reifyManyWithoutInstances ''Lift [''Info, ''Loc] (const True) >>=
    |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
```

I did not check other releases of `th-orphans`.

**Comment by RyanGlScott** [comment]
As far as I can tell, here are the causes of these two issues:

1. The `Duplicate instance declarations` issue is caused when using GHC 8.10 or later in combination with `th-reify-many-0.1.8` or older. Unfortunately, I can't find a corresponding issue on the `th-reify-many` issue tracker, but I do know that the issue was fixed in the `th-reify-many-0.1.9` release. (See mgsloan/th-reify-many@c9556ad38ca30e928a7eab7d535cbc5c9051ad05.)
2. The `Could not deduce (Lift ... RealWorld ...)` issue is caused when using GHC 8.10 or later in combination with `th-orphans-0.13.6` or older. See #27.

Accordingly, I've applied the following Hackage revisions:

1. I've revised `th-reify-many-0.1.8` and older to have `template-haskell <2.16` upper version bounds (i.e., only buildable with GHC <8.10).
2. I've also revised `th-orphans-0.13.6` and older to have `template-haskell <2.16` upper version bounds.

I believe this should take care of things, but do re-open this issue is something else is still misconfigured.

**Comment by BiscuitCookies** [comment]
Don't know if this is a similar issues but I had a similar error message when building my project

`th-orphans > src\Language\Haskell\TH\Instances.hs:478:2: error:
th-orphans >     The exact Name `x1_ae3z' is not in scope
th-orphans >       Probable cause: you used a unique Template Haskell name (NameU), 
th-orphans >       perhaps via newName, but did not bind it
th-orphans >       If that's it, then -ddump-splices might be useful
th-orphans >     |
th-orphans > 478 | $(reifyManyWithoutInstances ''Lift [''Info, ''Loc] ... 
th-orphans >     |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...`

Was trying to build with lts 19.16 and latest template haskell

**Comment by RyanGlScott** [comment]
It would be worth filing a separate issue about this, since Stackage LTS 19.16 contains `th-orphans-0.13.13`, which is a different version than the one discussed here. That being said, I can't reproduce the issue you're experiencing, so including more detailed instructions on how to reproduce the issue would be helpful. In particular, I don't know what you mean by "latest template haskell"—which `template-haskell` version in particular?
